# Generated by Django 4.2.3 on 2023-08-23 10:29

import app_advertisements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=128, validators=[app_advertisements.models.validate_title], verbose_name='заголовок'),
        ),
    ]
